### ISSUE TITLE
Fix version constraints

### ISSUE THREAD

**Issue by coord-e** [Sakuten/infrastructure#15]
{terraform, 各provider}のバージョン違いにより動かせないのを防ぐ

- [x] `version`キーを追加: `provider.tf`
- [x] どこかにterraformのバージョンの制限を書く
- [x] tfswitchを使うよう指示

**Comment by kvendingoldo** [comment]
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.
